### PR TITLE
Remove unused private field

### PR DESCRIPTION
**Pull request by pzygielo**
Looks like unused since c70cfaa54e2a8d07fbae4e84fd1827b668a7060a.

### CODE REVIEW

**Comment by jbescos** [comment]
Can we also remove it from constructors?

**Comment by pzygielo** [comment]
In this class - it's passed to `JsonParserImpl` I think.

**Comment by pzygielo** [comment]
@jbescos - Have I answered your question? (I might not see the modification you think about.)

Is there any change requested for this PR to be considered?

**Comment by jbescos** [comment]
Yes, thank you.

**Pull request merged**
